Adding Software requirements specification
EgorHubBrest/HRM pull request #2
Opened 2020-12-11 15:22 UTC by EgorHubBrest

Added a folder with SRS and project images.

2020-12-14 06:06 UTC, inauros commented on documents/SRS.md
> +This system will consist of two parts:databases and web applications. The database will be used for storing and processing information that will come from the web application. The web application wil
1. the database is responsible for storing information only
2. the web application is responsible for processing/managing information
3. the system should not provide users with information about work schedule and vacations (see step 12 for details)

2020-12-14 06:07 UTC, inauros commented on documents/SRS.md
> +Pic. 2.1 DFD diagram.
Please fix the diagram to display the arrows correctly

2020-12-14 06:14 UTC, inauros commented on documents/SRS.md
> +With this web application, users can manage the organization's employees and create reports on their work. The Manager will have access to such functions as: entering employee information, viewing em
The interactive calendar is not a part of this project. But if you want to implement it. This will be a great feature. :)

2020-12-14 06:19 UTC, inauros commented on documents/SRS.md
> +- Designation - designation of the department.
What is the purpose of this field?

2020-12-14 06:20 UTC, inauros commented on documents/SRS.md
> +<img src="https://github.com/EgorHubBrest/HRM/blob/subordinate/documents/pictures/lock2.png"  width="600" height="600">
The "confirm your email address" window is displayed twice.

2020-12-14 06:21 UTC, inauros commented on documents/SRS.md
> +#### 3.1.1 Login form
How should the system behave if incorrect data is entered?

2020-12-14 06:22 UTC, inauros commented on documents/SRS.md
> +#### 3.1.2 Registration
How should the system behave if the entered passwords do not match?

2020-12-14 06:24 UTC, inauros commented on documents/SRS.md
> +#### 3.3.2 New Department
How should the system behave if the entered department name already exists?

2020-12-14 06:25 UTC, inauros commented on documents/SRS.md
> +#### 3.3.4 Removing the Departament
How should the system behave if a user tries to delete a department to which there are associated employees?

2020-12-14 06:28 UTC, inauros commented on documents/SRS.md
> +#### 3.4.2 New Employee
What is the purpose of the "Company Details" section?

2020-12-14 06:35 UTC, inauros commented on documents/SRS.md
> +#### 3.4.1 Employee List
Search for employees born on a certain date or in the period between dates should be implemented (see the step 12 for details)

2020-12-14 06:35 UTC, inauros requested changes
Please update your pull request as follows:
1. remove the [documents/README.md](https://github.com/EgorHubBrest/HRM/blob/subordinate/documents/README.md) file
2. the main [README.md](https://github.com/EgorHubBrest/HRM/blob/subordinate/README.md) file should include details about project goal in English (see the step 4 description)

2020-12-17 14:48 UTC, EgorHubBrest commented on documents/SRS.md
> +- Designation - designation of the department.
describe the columns in the table

2020-12-17 14:49 UTC, EgorHubBrest commented on documents/SRS.md
> +#### 3.4.2 New Employee
1.This field is used to enter information about users in the company:ID, what department he works in,how much he earns, and so on

2020-12-18 13:53 UTC, inauros commented on documents/SRS.md
> +- Designation - designation of the department.
I meant the Designation column

2020-12-19 09:56 UTC, EgorHubBrest commented on documents/SRS.md
> +#### 3.4.2 New Employee
2.corrected the data type.
3.added text and picture describing this situation

2020-12-19 09:57 UTC, EgorHubBrest commented on documents/SRS.md
> +Pic. 2.1 DFD diagram.
fixed

2020-12-19 09:58 UTC, EgorHubBrest commented on documents/SRS.md
> +This system will consist of two parts:databases and web applications. The database will be used for storing and processing information that will come from the web application. The web application wil
Fixed to correct text

2020-12-19 09:58 UTC, EgorHubBrest commented on documents/SRS.md
> +<img src="https://github.com/EgorHubBrest/HRM/blob/subordinate/documents/pictures/lock2.png"  width="600" height="600">
Fixed

2020-12-19 09:59 UTC, EgorHubBrest commented on documents/SRS.md
> +#### 3.1.1 Login form
added text and picture describing this situation

2020-12-19 09:59 UTC, EgorHubBrest commented on documents/SRS.md
> +#### 3.1.2 Registration
added text and picture describing this situation

2020-12-19 09:59 UTC, EgorHubBrest commented on documents/SRS.md
> +#### 3.3.2 New Department
added text and picture describing this situation

2020-12-19 09:59 UTC, EgorHubBrest commented on documents/SRS.md
> +#### 3.3.4 Removing the Departament
added text and picture describing this situation

2020-12-19 09:59 UTC, EgorHubBrest commented on documents/SRS.md
> +#### 3.4.1 Employee List
Added filter by date

2020-12-22 09:34 UTC, EgorHubBrest commented on documents/SRS.md
> +- Designation - designation of the department.
This field indicates the main goal of this Department.for example:Department-IT, Designation-Create apps for Google.If you think it's unnecessary, I can remove it.

2020-12-23 09:08 UTC, merged